image: archlinux
packages:
  - unzip
  - git
  - jre-openjdk-headless
secrets:
  - e981d560-d8ad-4e0a-8e30-f45647576614
shell: false
sources:
- https://git.sr.ht/~poldi1405/go-ansi
tasks:
  - code-review: |
      cd go-ansi
      go test -v -coverprofile=coverage.out
      ~/sonarcloud_scan
